"""Initial migration after cleanup

Revision ID: a3f99f952a6a
Revises: 
Create Date: 2025-06-23 01:24:39.331508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f99f952a6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preserved_testimonial', schema=None) as batch_op:
        batch_op.drop_index('ix_preserved_testimonial_access_uuid')

    op.drop_table('preserved_testimonial')
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonial', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('preserved_testimonial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('access_uuid', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preserved_testimonial', schema=None) as batch_op:
        batch_op.create_index('ix_preserved_testimonial_access_uuid', ['access_uuid'], unique=1)

    # ### end Alembic commands ###
